name: rama_otaqu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  carousel_slider: ^5.1.1
  auto_route: ^10.1.0+1
  flutter_screenutil: ^5.9.3
  percent_indicator: ^4.2.5
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.9.2
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/illustrations/
    - assets/images/brands/
    - assets/images/statics/promos/

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 100
  integrations:
    image: true
    flutter_svg: true
    lottie: true